### ISSUE TITLE
mrcli company add_wizard fails with company_dns error

### ISSUE THREAD

**Issue by jgoodie** [mediumroast/mediumroast_js#50]
mrcli c --add_wizard     
                                                                                                                                               
file:///usr/local/lib/node_modules/mediumroast_js/src/cli/companyWizard.js:46
        this.env.DEFAULT.company_dns ? this.companyDNS = this.env.DEFAULT.company_dns : this.companyDNS = companyDNSUrl
                         ^

TypeError: Cannot read properties of undefined (reading 'company_dns')
    at new AddCompany (file:///usr/local/lib/node_modules/mediumroast_js/src/cli/companyWizard.js:46:26)
    at file:///usr/local/lib/node_modules/mediumroast_js/cli/mrcli-company.js:232:23

Node.js v21.4.0

**Comment by miha42-github** [comment]
The issue should be resolved.  The problem in the companyWizard.js module was the definition of the company_dns setting.  Essentially it should have been companyDNS and not company_dns.  The object declaration was also incorrect.  This should be resolved awaiting confirmation from @jgoodie.

**Comment by miha42-github** [comment]
The issue has been verified to work, closing.
