### ISSUE TITLE
mrcli add company wizard crashes on gathering firmographics getLatLong()

### ISSUE THREAD

**Issue by jgoodie** [mediumroast/mediumroast_js#69]
? Your company's name is? ProductPlan
? What type of company is this? Private
Set the company's type to [Private]
? What role should we assign to this company? Competitor
Set the company's role to [Competitor]
? What region is this company in? North, Meso and South America (AMER)
Set the company's region to [AMER]
Attempting to automatically discover company firmographics.
? No company matching [ProductPlan] found, try again? Yes
? Your company's name is? ProductPlan
? No company matching [ProductPlan] found, try again? No

No matching company found, starting manual company definition...
? What's the description? ProductPlan is a platform for product managers to align their teams, collaborate on their roadmaps, and measure the
impact of their work.
? What's the website? https://www.productplan.com/
? What's the street address? 836 Anacapa Street Suite 944
? What's the city? Santa Barbara
? What's the state or province? CA
? What's the country? USA
? What's the zip or postal code? 93101
? What's the phone number? 805-618-2975
? What's the wikipedia url? Unknown
? What's your industry search string? computer
? Please choose the most appropriate industry Computers and Computer Peripheral Equipment and Software
file:///usr/local/lib/node_modules/mediumroast_js/src/cli/companyWizard.js:576
            const [status, msg, [lat, long]] = await this.getLatLong(fullAddress)
                                ^

TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at AddCompany.doAutomatic (file:///usr/local/lib/node_modules/mediumroast_js/src/cli/companyWizard.js:576:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AddCompany.wizard (file:///usr/local/lib/node_modules/mediumroast_js/src/cli/companyWizard.js:755:21)
    at async file:///usr/local/lib/node_modules/mediumroast_js/cli/mrcli-company.js:230:19

**Comment by miha42-github** [comment]
@jgoodie fixed by changing the geocoding module, closing
