### ISSUE TITLE
Add sanity checks to check for full path or check for local dir

### ISSUE THREAD

**Issue by jgoodie** [mediumroast/mediumroast_js#82]
If a user does not provide a full path, either add a path sanity check or a check for a local dir.
Example below: I entered "temp" as the directory name instead of a full path name. This causes a crash and a stale github lockfile.
If you specify a relative path "./temp" then the mrcli will work as expected.

? It appears you'd like to create a new interaction, right? Yes
Checking if the mediumroast.io app is ready to add interactions ... Ok
? Which company are these interaction(s) associated to? ProductPlan
? What's the full path to the directory (e.g., /dir/subdir)? temp  <--- this will cause an error and leave a stale github lock

**Comment by miha42-github** [comment]
Fixed
